### ISSUE TITLE
Not working on the new v7 or v8 of the app

### ISSUE THREAD

**Issue by steve51184** [jcul/HaliphaxHideRoot#6]
Hi in on v7 and even the just released v8 of the Halifax app and this still isn't working I'm trying to set up online banking and I get past the 'phone call verification' but always get an 'app inacceptable, sorry we are experiencing technical problems please try again later' error so I've had to downgrade back to v6 till this is fixed

Halifax v6 apk: https://www.sendspace.com/file/luvrop

Halifax v6 apk (resigned so it won't show up in the play store): https://www.sendspace.com/file/785krw

**Comment by jcul** [comment]
Hi Steve,
Sorry I haven't had time to look into this, been very busy lately. And I'm off travelling now for a couple weeks, so won't be able to spend too much time on it.
Will look into it as soon as I can though.
I'm surprised it stopped working. Did it work for you at any point on v7? It seemed OK for me when I tested it, but I don't have my old rooted phone with me so I'm unsure of the exact version.
Jack

**Comment by steve51184** [comment]
Yeah neither v7 or v8 of the Halifax app worked for me at all with any
version of this mod

Halifax v6 + your mod v4 are what it's working for me

**Comment by markchalloner** [comment]
V7 works for me me on One Plus One Kitkat but I had to wipe the apps data and reenroll

**Comment by Overseergti** [comment]
V7 has always worked for me on the lloyds app. They've just updated to v8 and the module no longer works , good thing I backed up the v7 apk!

**Comment by Shaun7777** [comment]
Can anyone post a v7 apk for lloyds as I didn't back it up and it just updated for me. Thanks

**Comment by Meleelord** [comment]
Could anyone possibly post the v7 apk for Halifax?

**Comment by Meleelord** [comment]
Could you repost v6 please Steve? The link doesn't seem to work

**Comment by sbgillett** [comment]
V8 not working for me here either (Samsung GT-N7100). Can anyone post a link to the V6 or 7 apk?

**Comment by Overseergti** [comment]
Lloyds v7 apk: http://filesave.me/file/59031/Lloyds-v7-0-apk.html

**Comment by sbgillett** [comment]
Sorry, was looking for the Halifax V7 (or previous) app

**Comment by phoenix-frozen** [comment]
@steve51184 : Your link no longer works... could you re-upload? We're all hoping to downgrade back to v6

**Comment by steve51184** [comment]
Halifax v6 apk: https://www.sendspace.com/file/luvrop

**Comment by steve51184** [comment]
Does anyone have the Halifax v7 apk? I wanna see if I can get that working :)

**Comment by Overseergti** [comment]
The Lloyds v7 app now seems to not want to work - I assume they want me to upgrade to v8.

Any chance someone could pick this up in Jack's absence?
